# Bugs found only by running against real panel data. Synthetic tests missed all
# three, because synthetic data is generated by the same assumptions the code
# makes.

test_that("the time column may be a predictor when named outright", {
  # In growth data the predictor very often IS time (Reaction ~ Days,
  # weight ~ Time, distance ~ age). The time column used to be stripped from
  # the predictors unconditionally, which left `x` empty and every verb died
  # with "No predictors selected."
  skip_if_not_installed("lme4")
  data(sleepstudy, package = "lme4", envir = environment())

  fit <- fit_lm(sleepstudy, "Reaction", "Days", "Subject", time = "Days",
                min_train = 6L)
  expect_equal(fit$spec$x, "Days")
  expect_true(all(is.finite(metrics(fit, overall = TRUE)$rmse)))

  # A formula names it explicitly too.
  f2 <- fit_lm(sleepstudy, "Reaction", ~ Days, "Subject", time = "Days",
               min_train = 6L)
  expect_equal(f2$spec$x, "Days")
})

test_that("a range selector still does not sweep in the time column", {
  # The protection has to survive: only an EXPLICIT mention counts.
  d <- data.frame(id = rep(1:4, each = 20), day = rep(1:20, 4),
                  a = stats::rnorm(80), b = stats::rnorm(80))
  d$y <- d$a + stats::rnorm(80)
  # Columns are id, day, a, b, y -- positions 2:4 span the time column `day`.
  fit <- fit_lm(d, "y", 2:4, "id", time = "day", min_train = 10L)
  expect_false("day" %in% fit$spec$x)
  expect_setequal(fit$spec$x, c("a", "b"))
})

test_that("a predictor constant within every person is refused clearly", {
  # Theoph's `Wt` is a person-level covariate: constant inside each subject, so
  # a person-specific model cannot estimate it. This used to surface as NA
  # coefficients, then dropped people, then "Too few people with usable
  # coefficients" -- which names neither the cause nor the cure.
  th <- as.data.frame(datasets::Theoph)
  th$Subject <- as.character(th$Subject)

  expect_error(
    fit_lm(th, "conc", c("Time", "Wt"), "Subject", time = "Time",
           min_train = 6L),
    "constant within every person"
  )
  expect_error(
    test_subgroups(th, "conc", c("Time", "Wt"), "Subject"),
    "constant within every person"
  )

  # But a person-level covariate is perfectly fine in a POOLED model, and the
  # error must not fire there.
  pooled <- fit_lm(th, "conc", c("Time", "Wt"), "Subject", time = "Time",
                   scope = "pooled", min_train = 6L)
  expect_true(all(is.finite(metrics(pooled, overall = TRUE)$rmse)))
})

test_that("unbalanced panels split correctly within person", {
  # ChickWeight is unbalanced (2 to 12 observations per chick). The occasion
  # split built a logical vector per group and then tried to unscramble it,
  # which silently mis-mapped rows whenever group sizes differed.
  cw <- as.data.frame(datasets::ChickWeight)
  cw$Chick <- as.character(cw$Chick)

  expect_silent(
    h <- fit_heterogeneity(cw, "weight", "Time", "Chick", target = "gain",
                           num_splits = 4L, model = "linear", time = "Time")
  )
  expect_true(is.finite(heterogeneity(h, effect = "average")$estimate))
})

test_that("real panels run end to end", {
  skip_if_not_installed("lme4")
  data(sleepstudy, package = "lme4", envir = environment())

  # sleepstudy is the textbook random-slope dataset: people differ a lot in how
  # sleep deprivation hits them, so individual models must beat pooling.
  fit <- fit_lm(sleepstudy, "Reaction", "Days", "Subject", time = "Days",
                min_train = 6L)
  ov <- metrics(fit, overall = TRUE)
  rmse <- stats::setNames(ov$rmse, ov$scope)
  expect_lt(rmse[["individual"]], rmse[["pooled"]])

  # And the variation is continuous, not clustered: there are no discrete
  # subgroups of sleepers to find.
  expect_equal(test_subgroups(sleepstudy, "Reaction", "Days", "Subject")$k, 1L)
})
